In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , MinMaxScaler , OneHotEncoder , PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.dummy import DummyRegressor

1. Первичный анализ данных

In [2]:
# Загрузка данных
df = pd.read_csv('ToyotaCorolla.csv')
df.info() # Для преобразования категориальных переменных

<class 'pandas.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 39 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 1436 non-null   int64
 1   Model              1436 non-null   str
 2   Price              1436 non-null   int64
 3   Age_08_04          1436 non-null   int64
 4   Mfg_Month          1436 non-null   int64
 5   Mfg_Year           1436 non-null   int64
 6   KM                 1436 non-null   int64
 7   Fuel_Type          1436 non-null   str
 8   HP                 1436 non-null   int64
 9   Met_Color          1436 non-null   int64
 10  Color              1436 non-null   str
 11  Automatic          1436 non-null   int64
 12  CC                 1436 non-null   int64
 13  Doors              1436 non-null   int64
 14  Cylinders          1436 non-null   int64
 15  Gears              1436 non-null   int64
 16  Quarterly_Tax      1436 non-null   int64
 17  Weight             1436 non-null   int64
 18  Mfr_Guarantee      1436 non-null   int64
 19  BOVAG_Guarantee    1436 non-null   int64
 20  Guarantee_Period   1436 non-null   int64
 21  ABS                1436 non-null   int64
 22  Airbag_1           1436 non-null   int64
 23  Airbag_2           1436 non-null   int64
 24  Airco              1436 non-null   int64
 25  Automatic_airco    1436 non-null   int64
 26  Boardcomputer      1436 non-null   int64
 27  CD_Player          1436 non-null   int64
 28  Central_Lock       1436 non-null   int64
 29  Powered_Windows    1436 non-null   int64
 30  Power_Steering     1436 non-null   int64
 31  Radio              1436 non-null   int64
 32  Mistlamps          1436 non-null   int64
 33  Sport_Model        1436 non-null   int64
 34  Backseat_Divider   1436 non-null   int64
 35  Metallic_Rim       1436 non-null   int64
 36  Radio_cassette     1436 non-null   int64
 37  Parking_Assistant  1436 non-null   int64
 38  Tow_Bar            1436 non-null   int64
dtypes: int64(36), str(3)
memory usage: 437.7 KB

In [3]:
df.head(39)

,Id,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
0,1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13500,23,10,2002,46986,Diesel,90,1,...,1,1,0,0,0,1,0,0,0,0
1,2,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13750,23,10,2002,72937,Diesel,90,1,...,0,1,0,0,0,1,0,0,0,0
2,3,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13950,24,9,2002,41711,Diesel,90,1,...,0,1,0,0,0,1,0,0,0,0
3,4,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,14950,26,7,2002,48000,Diesel,90,0,...,0,1,0,0,0,1,0,0,0,0
4,5,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,13750,30,3,2002,38500,Diesel,90,0,...,1,1,0,1,0,1,0,0,0,0
5,6,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,12950,32,1,2002,61000,Diesel,90,0,...,1,1,0,1,0,1,0,0,0,0
6,7,TOYOTA Corolla 2.0 D4D 90 3DR TERRA 2/3-Doors,16900,27,6,2002,94612,Diesel,90,1,...,1,1,0,0,1,1,0,0,0,0
7,8,TOYOTA Corolla 2.0 D4D 90 3DR TERRA 2/3-Doors,18600,30,3,2002,75889,Diesel,90,1,...,1,1,0,0,0,1,0,0,0,0
8,9,TOYOTA Corolla 1800 T SPORT VVT I 2/3-Doors,21500,27,6,2002,19700,Petrol,192,0,...,1,1,1,0,0,0,1,1,0,0
9,10,TOYOTA Corolla 1.9 D HATCHB TERRA 2/3-Doors,12950,23,10,2002,71138,Diesel,69,0,...,0,1,0,0,0,1,0,0,0,0
10,11,TOYOTA Corolla 1.8 VVTL-i T-Sport 3-Drs 2/3-Doors,20950,25,8,2002,31461,Petrol,192,0,...,1,1,0,0,0,0,1,0,0,0
11,12,TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT BNS 2...,19950,22,11,2002,43610,Petrol,192,0,...,1,1,0,1,1,1,1,0,0,0
12,13,TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-D...,19600,25,8,2002,32189,Petrol,192,0,...,1,1,0,1,1,1,1,0,0,0
13,14,TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-D...,21500,31,2,2002,23000,Petrol,192,1,...,1,1,0,1,1,1,1,0,0,0
14,15,TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-D...,22500,32,1,2002,34131,Petrol,192,1,...,1,1,0,1,1,1,1,0,0,0
15,16,TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-D...,22000,28,5,2002,18739,Petrol,192,0,...,1,1,0,1,1,1,1,0,0,0
16,17,TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-D...,22750,30,3,2002,34000,Petrol,192,1,...,1,1,0,1,0,1,1,0,0,0
17,18,TOYOTA Corolla 1.6 VVTI Linea Terra Comfort 2/...,17950,24,9,2002,21716,Petrol,110,1,...,1,1,1,0,0,0,0,1,0,1
18,19,TOYOTA Corolla 1.6 16v L.SOL 2/3-Doors,16750,24,9,2002,25563,Petrol,110,0,...,1,1,0,1,0,0,0,0,0,0
19,20,TOYOTA Corolla 1.6 16V VVT I 3DR TERRA 2/3-Doors,16950,30,3,2002,64359,Petrol,110,1,...,1,1,0,0,1,1,0,0,0,0
20,21,TOYOTA Corolla 1.6 16V VVT I 3DR TERRA 2/3-Doors,15950,30,3,2002,67660,Petrol,110,1,...,1,1,0,0,1,1,0,0,0,1
21,22,TOYOTA Corolla 1.6 16V VVT I 3DR SOL AUT4 2/3-...,16950,29,4,2002,43905,Petrol,110,0,...,1,1,0,1,1,1,0,0,0,0
22,23,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,15950,28,5,2002,56349,Petrol,110,1,...,1,1,0,1,1,1,1,0,0,1
23,24,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,16950,28,5,2002,32220,Petrol,110,1,...,1,1,0,1,1,1,0,0,0,0
24,25,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,16250,29,4,2002,25813,Petrol,110,1,...,1,1,0,1,1,1,0,0,0,0
25,26,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,15950,25,8,2002,28450,Petrol,110,1,...,1,1,0,1,1,1,1,0,0,1
26,27,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,17495,27,6,2002,34545,Petrol,110,1,...,1,1,0,1,0,1,1,0,0,0
27,28,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,15750,29,4,2002,41415,Petrol,110,1,...,1,1,0,1,1,1,1,0,0,0
28,29,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,16950,28,5,2002,44142,Petrol,110,0,...,1,1,0,1,1,1,0,0,0,0
29,30,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,17950,30,3,2002,11090,Petrol,110,1,...,1,1,0,1,1,1,0,0,0,0
30,31,TOYOTA Corolla 1.4 VVTI Linea Terra 2/3-Doors,12950,29,4,2002,9750,Petrol,97,1,...,0,1,1,0,0,0,0,1,0,0
31,32,TOYOTA Corolla 1.4 16V VVT I 3DR TERRA COMFORT...,15750,22,11,2002,35199,Petrol,97,1,...,1,1,0,0,1,1,1,0,0,1
32,33,TOYOTA Corolla 1.4 16V VVT I 3DR TERRA COMFORT...,15950,27,6,2002,29510,Petrol,97,1,...,1,1,0,0,1,1,0,0,0,0
33,34,TOYOTA Corolla 1.4 16V VVT I 3DR TERRA COMFORT...,14950,26,7,2002,32692,Petrol,97,1,...,1,1,0,0,1,1,0,0,0,0
34,35,TOYOTA Corolla 1.4 16V VVT I 3DR TERRA COMFORT...,15500,22,11,2002,41000,Petrol,97,1,...,1,1,0,0,1,1,0,0,0,0
35,36,TOYOTA Corolla 1.4 16V VVT I 3DR TERRA COMFORT...,15750,26,7,2002,43000,Petrol,97,0,...,1,1,0,0,1,1,0,0,0,0
36,37,TOYOTA Corolla 1.4 16V VVT I 3DR TERRA COMFORT...,15950,25,8,2002,25000,Petrol,97,0,...,1,1,0,0,1,1,0,0,0,0
37,38,TOYOTA Corolla 1.4 16V VVT I 3DR TERRA 2/3-Doors,14950,23,10,2002,10000,Petrol,97,1,...,1,1,0,0,1,1,0,0,0,0
38,39,TOYOTA Corolla 1.4 16V VVT I 3DR TERRA 2/3-Doors,15750,32,1,2002,25329,Petrol,97,1,...,1,1,0,0,1,1,0,0,0,0

In [4]:
df.tail()

,Id,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
1431,1438,TOYOTA Corolla 1.3 16V HATCHB G6 2/3-Doors,7500,69,12,1998,20544,Petrol,86,1,...,1,1,0,1,1,1,0,0,0,0
1432,1439,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,10845,72,9,1998,19000,Petrol,86,0,...,0,1,0,0,1,1,0,0,0,0
1433,1440,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,8500,71,10,1998,17016,Petrol,86,0,...,0,1,0,0,0,1,0,0,0,0
1434,1441,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,7250,70,11,1998,16916,Petrol,86,1,...,0,0,0,0,0,1,0,0,0,0
1435,1442,TOYOTA Corolla 1.6 LB LINEA TERRA 4/5-Doors,6950,76,5,1998,1,Petrol,110,0,...,0,1,0,0,0,0,0,0,0,0

In [5]:
df.describe(include='all')

,Id,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
count,1436.000000,1436,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436,1436.000000,1436.000000,...,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000
unique,NaN,319,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-...,NaN,NaN,NaN,NaN,NaN,Petrol,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,109,NaN,NaN,NaN,NaN,NaN,1264,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,721.555014,NaN,10730.824513,55.947075,5.548747,1999.625348,68533.259749,NaN,101.502089,0.674791,...,0.561978,0.977716,0.146240,0.256964,0.300139,0.770195,0.204735,0.145543,0.002786,0.277855
std,416.476890,NaN,3626.964585,18.599988,3.354085,1.540722,37506.448872,NaN,14.981080,0.468616,...,0.496317,0.147657,0.353469,0.437111,0.458478,0.420854,0.403649,0.352770,0.052723,0.448098
min,1.000000,NaN,4350.000000,1.000000,1.000000,1998.000000,1.000000,NaN,69.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,361.750000,NaN,8450.000000,44.000000,3.000000,1998.000000,43000.000000,NaN,90.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,721.500000,NaN,9900.000000,61.000000,5.000000,1999.000000,63389.500000,NaN,110.000000,1.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,1081.250000,NaN,11950.000000,70.000000,8.000000,2001.000000,87020.750000,NaN,110.000000,1.000000,...,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000
max,1442.000000,NaN,32500.000000,80.000000,12.000000,2004.000000,243000.000000,NaN,192.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
df.isnull().sum() # проверяем количество пропущенных значений каждого признака

Id                   0
Model                0
Price                0
Age_08_04            0
Mfg_Month            0
Mfg_Year             0
KM                   0
Fuel_Type            0
HP                   0
Met_Color            0
Color                0
Automatic            0
CC                   0
Doors                0
Cylinders            0
Gears                0
Quarterly_Tax        0
Weight               0
Mfr_Guarantee        0
BOVAG_Guarantee      0
Guarantee_Period     0
ABS                  0
Airbag_1             0
Airbag_2             0
Airco                0
Automatic_airco      0
Boardcomputer        0
CD_Player            0
Central_Lock         0
Powered_Windows      0
Power_Steering       0
Radio                0
Mistlamps            0
Sport_Model          0
Backseat_Divider     0
Metallic_Rim         0
Radio_cassette       0
Parking_Assistant    0
Tow_Bar              0
dtype: int64

In [11]:
to_drop = ['Id', 'Model', 'Mfg_Year', 'Mfg_Month', 'Cylinders', 'Color']
df_cleaned = df.drop(columns=to_drop)

In [12]:
df_final = pd.get_dummies(df_cleaned, columns=['Fuel_Type'], drop_first=True)

2. Разбиение выборки и последующая нормализация

In [13]:
X = df_final.drop('Price', axis = 1)
y = df_final['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)

Shape of X_train:  (1077, 33)
Shape of X_test:  (359, 33)

In [14]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

**Обязательно объясните текстом:**
* **Сделали ли вы предобработку данных для случайного леса? Отличалась ли она от предобработки данных для линейной модели? Если до, то почему?** Да, сделал, но на всякий случай, хоть необязательно это для случайного леса, в отличие от линейной модели. Для случайного леса характерен алгоритм основанный на деревьях решений, которые ищут оптимальный порог разделения
* **Как именно вы разделили выборку?** 80/20
* **На сколько частей нужно делить выборку при использовании кросс-валидации?** По стандарту 5 или 10, а так на k равных частей
* **Можно ли не использовать кросс-валидацию? Если да, то как делить выборку в таком случае?** Можно, если мы хотим быстрый результат или много данных. Как делить? На train, test и validation

3. Написание модели и последующее обучение (Сравнение 2х моделей при глубине 5)

In [16]:
rf_model = RandomForestRegressor(n_estimators=100, max_depth=5, random_state=42)
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)

In [17]:
dt_model = DecisionTreeRegressor(max_depth=5, random_state=42)
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)

In [18]:
print(f"random Forest r2: {r2_score(y_test, y_pred):.4f}, mae: {mean_absolute_error(y_test, y_pred):.2f}")
print(f"decision Tree r2: {r2_score(y_test, dt_pred):.4f}, mae: {mean_absolute_error(y_test, dt_pred):.2f}")

random Forest r2: 0.9153, mae: 822.14
decision Tree r2: 0.8970, mae: 902.39

**Вопросы для анализа:**
* **Сравнение скорости:** сравните, какая модель обучалась быстрее. Быстрее оказалась модель дерева решений
* **Можно ли добиться одинаковой или близкой к одинаковой скорости?** Чисто технически - да, но есть нюансы, такие как потеря точности, к примеру, при уменьшении количества деревьев или модель будет очень глубокой
* **Сравнение качества:** сравните результаты одного дерева и случайного леса. Тут побеждает случайный лес, судя по оценкам. Одно дерево склонно к переобучению, а лес борется с этим путем усреднения ответов множества деревьев. Более высокий коэффициент детерминации у леса говорит о том, что эта модель лучше понимает общую логику рынка подержанных машин и будет стабильнее работать на новых данных.

4. Оценка качества и сравнение моделей (Случайный лес и линейная регрессия)

Сравнение показало, что случайный лес стал лидером по точности, опередив линейную регрессию и одиночное дерево. Это объясняется способностью леса усреднять ошибки множества деревьев и находить сложные нелинейные связи. Одиночное дерево обучается быстрее всех, но проигрывает в точности из-за склонности к переобучению. Линейная регрессия показала стабильный результат, но уступила лесу в способности учитывать взаимодействие признаков. Таким образом, для достижения максимальной точности был выбран случайный лес.

**Ответьте на следующие вопросы: (если еще не отвечали в части про лин. рег)**
1. **Какие метрики вы использовали для сравнения моделей?** (Обоснуйте выбор: например, почему RMSE, а не MAE, или наоборот. Зачем нужен $R^2$?). Использовались $R^2$, MAE и RMSE. $R^2$ нужен для оценки доли объясненной дисперсии (насколько модель в целом поняла данные). MAE была выбрана для оценки средней ошибки в реальных деньгах, так как она более понятна человеку, а RMSE — для строгого учета крупных промахов модели
2. **На какой части выборки вы считали метрики?**  Все метрики рассчитывались исключительно на тестовой выборке, которую модель не видела в процессе обучения. Это гарантирует объективность оценки.
3. **Какая модель по итогу справилась лучше?** Лучше всех справился Случайный лес (Random Forest). Он показал самый высокий коэффициент детерминации ($R^2 = 0.9153$) и самую низкую среднюю ошибку ($MAE = 822.14$)
4. **Насколько хорошие получились результаты?** Результаты очень хорошие. Значение $R^2 > 0.9$ говорит о высокой точности модели, а средняя ошибка около 822 евро при стоимости машин в 10–15 тысяч является приемлемой для рыночной оценки подержанных авто